import {GLOBS} from '../utils/globs.js';

/** @type {import('oxlint').OxlintConfig} */
const browser = {
	plugins: [],
	categories: {
		correctness: 'off',
	},
	env: {
		builtin: true,
	},
	overrides: [
		{
			files: [GLOBS.JS, GLOBS.TS],
			rules: {
				'no-restricted-globals': [
					'error',
					'addEventListener',
					'blur',
					'close',
					'closed',
					'confirm',
					'defaultStatus',
					'defaultstatus',
					'event',
					'external',
					'find',
					'focus',
					'frameElement',
					'frames',
					'history',
					'innerHeight',
					'innerWidth',
					'length',
					'location',
					'locationbar',
					'menubar',
					'moveBy',
					'moveTo',
					'name',
					'onblur',
					'onerror',
					'onfocus',
					'onload',
					'onresize',
					'onunload',
					'open',
					'opener',
					'opera',
					'outerHeight',
					'outerWidth',
					'pageXOffset',
					'pageYOffset',
					'parent',
					'print',
					'removeEventListener',
					'resizeBy',
					'resizeTo',
					'screen',
					'screenLeft',
					'screenTop',
					'screenX',
					'screenY',
					'scroll',
					'scrollbars',
					'scrollBy',
					'scrollTo',
					'scrollX',
					'scrollY',
					'self',
					'status',
					'statusbar',
					'stop',
					'toolbar',
					'top',
				],
			},
			env: {
				browser: true,
				es2026: true,
			},
		},
	],
};

export default browser;
