/** @type {import('oxlint').OxlintConfig} */
const javascript = {
	plugins: ['import', 'oxc', 'promise', 'unicorn'],
	categories: {
		correctness: 'error',
		suspicious: 'error',
		pedantic: 'error',
		perf: 'error',
	},
	env: {
		builtin: true,
		es2026: true,
	},
	rules: {
		'capitalized-comments': 'off',
		'import/extensions': [
			'error',
			'always',
			{
				ignorePackages: true,
			},
		],
		'import/first': 'error',
		'import/max-dependencies': 'off',
		'import/newline-after-import': 'error',
		'import/no-amd': 'error',
		'import/no-anonymous-default-export': 'off',
		'import/no-cycle': 'off',
		'import/no-duplicates': [
			'error',
			{
				'prefer-inline': false,
			},
		],
		'import/no-mutable-exports': 'error',
		'import/no-named-default': 'error',
		'import/no-unassigned-import': 'off',
		'import/no-webpack-loader-syntax': 'error',
		'max-classes-per-file': 'off',
		'max-depth': 'off',
		'max-lines': 'off',
		'max-lines-per-function': 'off',
		'max-nested-callbacks': 'off',
		'no-empty': 'error',
		'no-inline-comments': 'off',
		'no-negated-condition': 'off',
		'no-nested-ternary': 'off',
		'no-regex-spaces': 'error',
		'no-warning-comments': 'off',
		'promise/avoid-new': 'off',
		'promise/catch-or-return': 'error',
		'promise/no-nesting': 'warn',
		'promise/no-return-wrap': [
			'error',
			{
				allowReject: true,
			},
		],
		'promise/param-names': 'error',
		'promise/prefer-await-to-then': 'error',
		'require-unicode-regexp': 'off',
		'sort-vars': 'off',
		'unicorn/catch-error-name': 'error',
		'unicorn/consistent-date-clone': 'error',
		'unicorn/consistent-existence-index-check': 'error',
		'unicorn/consistent-function-scoping': 'off',
		'unicorn/consistent-template-literal-escape': 'error',
		'unicorn/custom-error-definition': 'off',
		'unicorn/empty-brace-spaces': 'error',
		'unicorn/error-message': 'error',
		'unicorn/filename-case': 'error',
		'unicorn/import-style': 'error',
		'unicorn/no-abusive-eslint-disable': 'error',
		'unicorn/no-anonymous-default-export': 'error',
		'unicorn/no-array-for-each': 'error',
		'unicorn/no-array-method-this-argument': 'error',
		'unicorn/no-array-reduce': 'error',
		'unicorn/no-await-expression-member': 'error',
		'unicorn/no-console-spaces': 'error',
		'unicorn/no-document-cookie': 'error',
		'unicorn/no-magic-array-flat-depth': 'error',
		'unicorn/no-nested-ternary': 'error',
		'unicorn/no-null': 'off',
		'unicorn/no-process-exit': 'error',
		'unicorn/no-unreadable-array-destructuring': 'error',
		'unicorn/no-useless-collection-argument': 'error',
		'unicorn/no-useless-error-capture-stack-trace': 'error',
		'unicorn/no-useless-undefined': 'off',
		'unicorn/no-zero-fractions': 'error',
		'unicorn/number-literal-case': 'error',
		'unicorn/numeric-separators-style': 'error',
		'unicorn/prefer-array-index-of': 'error',
		'unicorn/prefer-bigint-literals': 'error',
		'unicorn/prefer-class-fields': 'error',
		'unicorn/prefer-classlist-toggle': 'error',
		'unicorn/prefer-default-parameters': 'error',
		'unicorn/prefer-dom-node-text-content': 'error',
		'unicorn/prefer-export-from': 'error',
		'unicorn/prefer-global-this': 'error',
		'unicorn/prefer-import-meta-properties': 'off',
		'unicorn/prefer-includes': 'error',
		'unicorn/prefer-keyboard-event-key': 'error',
		'unicorn/prefer-logical-operator-over-ternary': 'error',
		'unicorn/prefer-modern-dom-apis': 'error',
		'unicorn/prefer-modern-math-apis': 'error',
		'unicorn/prefer-module': 'error',
		'unicorn/prefer-negative-index': 'error',
		'unicorn/prefer-node-protocol': 'error',
		'unicorn/prefer-number-properties': 'error',
		'unicorn/prefer-object-from-entries': 'error',
		'unicorn/prefer-optional-catch-binding': 'error',
		'unicorn/prefer-reflect-apply': 'error',
		'unicorn/prefer-response-static-json': 'error',
		'unicorn/prefer-spread': 'error',
		'unicorn/prefer-string-raw': 'off',
		'unicorn/prefer-string-trim-start-end': 'error',
		'unicorn/prefer-structured-clone': 'error',
		'unicorn/prefer-ternary': 'off',
		'unicorn/relative-url-style': 'error',
		'unicorn/require-array-join-separator': 'error',
		'unicorn/require-module-attributes': 'error',
		'unicorn/require-post-message-target-origin': 'off',
		'unicorn/switch-case-braces': 'error',
		'unicorn/switch-case-break-position': 'error',
		'unicorn/text-encoding-identifier-case': 'error',
		'unicorn/throw-new-error': 'error',
	},
};

export default javascript;
