import {GLOBS} from '../utils/globs.js';

/** @type {import('oxlint').OxlintConfig} */
const typescript = {
	plugins: [],
	categories: {
		correctness: 'off',
	},
	options: {
		typeAware: true,
	},
	env: {
		builtin: true,
	},
	overrides: [
		{
			files: [GLOBS.TS],
			rules: {
				'constructor-super': 'error',
				'for-direction': 'error',
				'getter-return': 'error',
				'no-async-promise-executor': 'error',
				'no-case-declarations': 'error',
				'no-class-assign': 'error',
				'no-compare-neg-zero': 'error',
				'no-cond-assign': 'error',
				'no-const-assign': 'error',
				'no-constant-binary-expression': 'error',
				'no-constant-condition': 'error',
				'no-control-regex': 'error',
				'no-debugger': 'error',
				'no-delete-var': 'error',
				'no-dupe-class-members': 'error',
				'no-dupe-else-if': 'error',
				'no-dupe-keys': 'error',
				'no-duplicate-case': 'error',
				'no-empty': 'error',
				'no-empty-character-class': 'error',
				'no-empty-pattern': 'error',
				'no-empty-static-block': 'error',
				'no-ex-assign': 'error',
				'no-extra-boolean-cast': 'error',
				'no-fallthrough': 'error',
				'no-func-assign': 'error',
				'no-global-assign': 'error',
				'no-import-assign': 'error',
				'no-invalid-regexp': 'error',
				'no-irregular-whitespace': 'error',
				'no-loss-of-precision': 'error',
				'no-misleading-character-class': 'error',
				'no-new-native-nonconstructor': 'error',
				'no-nonoctal-decimal-escape': 'error',
				'no-obj-calls': 'error',
				'no-prototype-builtins': 'error',
				'no-redeclare': 'error',
				'no-regex-spaces': 'error',
				'no-self-assign': 'error',
				'no-setter-return': 'error',
				'no-shadow-restricted-names': 'error',
				'no-sparse-arrays': 'error',
				'no-this-before-super': 'error',
				'no-unassigned-vars': 'error',
				'no-unexpected-multiline': 'error',
				'no-unreachable': 'error',
				'no-unsafe-finally': 'error',
				'no-unsafe-negation': 'error',
				'no-unsafe-optional-chaining': 'error',
				'no-unused-labels': 'error',
				'no-unused-private-class-members': 'off',
				'no-unused-vars': 'off',
				'no-useless-backreference': 'error',
				'no-useless-catch': 'error',
				'no-useless-escape': 'error',
				'no-with': 'error',
				'preserve-caught-error': 'error',
				'require-yield': 'error',
				'use-isnan': 'error',
				'valid-typeof': 'error',
				'import/namespace': 'off',
				'import/default': 'error',
				'import/no-named-as-default': 'error',
				'import/no-named-as-default-member': 'error',
				'import/no-duplicates': [
					'error',
					{
						'prefer-inline': false,
					},
				],
				'promise/always-return': 'error',
				'promise/no-return-wrap': [
					'error',
					{
						allowReject: true,
					},
				],
				'promise/param-names': 'error',
				'promise/catch-or-return': 'error',
				'promise/no-nesting': 'warn',
				'promise/no-promise-in-callback': 'warn',
				'promise/no-callback-in-promise': 'warn',
				'promise/avoid-new': 'off',
				'promise/no-new-statics': 'error',
				'promise/valid-params': 'error',
				'no-negated-condition': 'off',
				'no-nested-ternary': 'off',
				'unicorn/catch-error-name': 'error',
				'unicorn/consistent-assert': 'error',
				'unicorn/consistent-date-clone': 'error',
				'unicorn/consistent-empty-array-spread': 'error',
				'unicorn/consistent-existence-index-check': 'error',
				'unicorn/consistent-function-scoping': 'off',
				'unicorn/consistent-template-literal-escape': 'error',
				'unicorn/custom-error-definition': 'off',
				'unicorn/empty-brace-spaces': 'error',
				'unicorn/error-message': 'error',
				'unicorn/escape-case': 'error',
				'unicorn/explicit-length-check': 'error',
				'unicorn/filename-case': 'error',
				'unicorn/import-style': 'error',
				'unicorn/new-for-builtins': 'error',
				'unicorn/no-abusive-eslint-disable': 'error',
				'unicorn/no-accessor-recursion': 'error',
				'unicorn/no-anonymous-default-export': 'error',
				'unicorn/no-array-callback-reference': 'error',
				'unicorn/no-array-fill-with-reference-type': 'error',
				'unicorn/no-array-for-each': 'error',
				'unicorn/no-array-method-this-argument': 'error',
				'unicorn/no-array-reduce': 'error',
				'unicorn/no-array-reverse': 'error',
				'unicorn/no-array-sort': 'error',
				'unicorn/no-await-expression-member': 'error',
				'unicorn/no-await-in-promise-methods': 'error',
				'unicorn/no-console-spaces': 'error',
				'unicorn/no-document-cookie': 'error',
				'unicorn/no-empty-file': 'error',
				'unicorn/no-hex-escape': 'error',
				'unicorn/no-immediate-mutation': 'error',
				'unicorn/no-instanceof-builtins': 'error',
				'unicorn/no-invalid-fetch-options': 'error',
				'unicorn/no-invalid-remove-event-listener': 'error',
				'unicorn/no-lonely-if': 'error',
				'unicorn/no-magic-array-flat-depth': 'error',
				'unicorn/no-negated-condition': 'error',
				'unicorn/no-negation-in-equality-check': 'error',
				'unicorn/no-nested-ternary': 'error',
				'unicorn/no-new-array': 'error',
				'unicorn/no-new-buffer': 'error',
				'unicorn/no-null': 'off',
				'unicorn/no-object-as-default-parameter': 'error',
				'unicorn/no-process-exit': 'error',
				'unicorn/no-single-promise-in-promise-methods': 'error',
				'unicorn/no-static-only-class': 'error',
				'unicorn/no-thenable': 'error',
				'unicorn/no-this-assignment': 'error',
				'unicorn/no-typeof-undefined': 'error',
				'unicorn/no-unnecessary-array-flat-depth': 'error',
				'unicorn/no-unnecessary-array-splice-count': 'error',
				'unicorn/no-unnecessary-await': 'error',
				'unicorn/no-unnecessary-slice-end': 'error',
				'unicorn/no-unreadable-array-destructuring': 'error',
				'unicorn/no-unreadable-iife': 'error',
				'unicorn/no-useless-collection-argument': 'error',
				'unicorn/no-useless-error-capture-stack-trace': 'error',
				'unicorn/no-useless-fallback-in-spread': 'error',
				'unicorn/no-useless-length-check': 'error',
				'unicorn/no-useless-promise-resolve-reject': 'error',
				'unicorn/no-useless-spread': 'error',
				'unicorn/no-useless-switch-case': 'error',
				'unicorn/no-useless-undefined': 'off',
				'unicorn/no-zero-fractions': 'error',
				'unicorn/number-literal-case': 'error',
				'unicorn/numeric-separators-style': 'error',
				'unicorn/prefer-add-event-listener': 'error',
				'unicorn/prefer-array-find': 'error',
				'unicorn/prefer-array-flat': 'error',
				'unicorn/prefer-array-flat-map': 'error',
				'unicorn/prefer-array-index-of': 'error',
				'unicorn/prefer-array-some': 'error',
				'unicorn/prefer-at': 'error',
				'unicorn/prefer-bigint-literals': 'error',
				'unicorn/prefer-blob-reading-methods': 'error',
				'unicorn/prefer-class-fields': 'error',
				'unicorn/prefer-classlist-toggle': 'error',
				'unicorn/prefer-code-point': 'error',
				'unicorn/prefer-date-now': 'error',
				'unicorn/prefer-default-parameters': 'error',
				'unicorn/prefer-dom-node-append': 'error',
				'unicorn/prefer-dom-node-remove': 'error',
				'unicorn/prefer-dom-node-text-content': 'error',
				'unicorn/prefer-event-target': 'error',
				'unicorn/prefer-export-from': 'error',
				'unicorn/prefer-global-this': 'error',
				'unicorn/prefer-import-meta-properties': 'off',
				'unicorn/prefer-includes': 'error',
				'unicorn/prefer-keyboard-event-key': 'error',
				'unicorn/prefer-logical-operator-over-ternary': 'error',
				'unicorn/prefer-math-min-max': 'error',
				'unicorn/prefer-math-trunc': 'error',
				'unicorn/prefer-modern-dom-apis': 'error',
				'unicorn/prefer-modern-math-apis': 'error',
				'unicorn/prefer-module': 'error',
				'unicorn/prefer-native-coercion-functions': 'error',
				'unicorn/prefer-negative-index': 'error',
				'unicorn/prefer-node-protocol': 'error',
				'unicorn/prefer-number-properties': 'error',
				'unicorn/prefer-object-from-entries': 'error',
				'unicorn/prefer-optional-catch-binding': 'error',
				'unicorn/prefer-prototype-methods': 'error',
				'unicorn/prefer-query-selector': 'error',
				'unicorn/prefer-reflect-apply': 'error',
				'unicorn/prefer-regexp-test': 'error',
				'unicorn/prefer-response-static-json': 'error',
				'unicorn/prefer-set-has': 'error',
				'unicorn/prefer-set-size': 'error',
				'unicorn/prefer-single-call': 'error',
				'unicorn/prefer-spread': 'error',
				'unicorn/prefer-string-raw': 'off',
				'unicorn/prefer-string-replace-all': 'error',
				'unicorn/prefer-string-slice': 'error',
				'unicorn/prefer-string-starts-ends-with': 'error',
				'unicorn/prefer-string-trim-start-end': 'error',
				'unicorn/prefer-structured-clone': 'error',
				'unicorn/prefer-ternary': 'off',
				'unicorn/prefer-top-level-await': 'error',
				'unicorn/prefer-type-error': 'error',
				'unicorn/relative-url-style': 'error',
				'unicorn/require-array-join-separator': 'error',
				'unicorn/require-module-attributes': 'error',
				'unicorn/require-module-specifiers': 'error',
				'unicorn/require-number-to-fixed-digits-argument': 'error',
				'unicorn/require-post-message-target-origin': 'off',
				'unicorn/switch-case-braces': 'error',
				'unicorn/switch-case-break-position': 'error',
				'unicorn/text-encoding-identifier-case': 'error',
				'unicorn/throw-new-error': 'error',
				'default-param-last': 'error',
				'no-array-constructor': 'error',
				'no-empty-function': 'error',
				'no-loop-func': 'error',
				'no-void': [
					'error',
					{
						allowAsStatement: true,
					},
				],
				'no-restricted-imports': [
					'error',
					{
						paths: ['error', 'domain', 'freelist', 'smalloc', 'punycode', 'sys', 'querystring', 'colors'],
					},
				],
				'no-throw-literal': 'off',
				'no-unused-expressions': 'error',
				'no-useless-constructor': 'error',
				'prefer-promise-reject-errors': 'off',
				'default-case': 'off',
				'no-duplicate-imports': 'off',
				'typescript/adjacent-overload-signatures': 'error',
				'typescript/array-type': [
					'error',
					{
						default: 'array-simple',
					},
				],
				'typescript/await-thenable': 'error',
				'typescript/ban-ts-comment': [
					'error',
					{
						'ts-expect-error': 'allow-with-description',
						minimumDescriptionLength: 4,
					},
				],
				'typescript/ban-tslint-comment': 'error',
				'typescript/no-restricted-types': [
					'error',
					{
						types: {
							object: {
								message:
									'The `object` type is hard to use. Use `Record<string, unknown>` instead. See: https://github.com/typescript-eslint/typescript-eslint/pull/848',
								fixWith: 'Record<string, unknown>',
							},
							Buffer: {
								message: 'Use Uint8Array instead. See: https://sindresorhus.com/blog/goodbye-nodejs-buffer',
								suggest: ['Uint8Array'],
							},
							'[]': "Don't use the empty array type `[]`. It only allows empty arrays. Use `SomeType[]` instead.",
							'[[]]':
								"Don't use `[[]]`. It only allows an array with a single element which is an empty array. Use `SomeType[][]` instead.",
							'[[[]]]': "Don't use `[[[]]]`. Use `SomeType[][][]` instead.",
							'[[[[]]]]': 'ur drunk 🤡',
							'[[[[[]]]]]': '🦄💥',
						},
					},
				],
				'typescript/class-literal-property-style': ['error', 'getters'],
				'typescript/consistent-generic-constructors': ['error', 'constructor'],
				'typescript/consistent-indexed-object-style': 'error',
				'typescript/dot-notation': 'error',
				'typescript/consistent-type-assertions': [
					'error',
					{
						assertionStyle: 'as',
						objectLiteralTypeAssertions: 'allow-as-parameter',
					},
				],
				'typescript/consistent-type-definitions': ['error', 'type'],
				'typescript/consistent-type-exports': [
					'error',
					{
						fixMixedExportsWithInlineTypeSpecifier: true,
					},
				],
				'typescript/consistent-type-imports': [
					'error',
					{
						fixStyle: 'inline-type-imports',
					},
				],
				'typescript/no-base-to-string': 'error',
				'typescript/no-array-delete': 'error',
				'typescript/no-confusing-void-expression': 'error',
				'typescript/no-deprecated': 'error',
				'typescript/no-duplicate-enum-values': 'error',
				'typescript/no-duplicate-type-constituents': 'error',
				'typescript/no-dynamic-delete': 'error',
				'typescript/no-empty-interface': [
					'error',
					{
						allowSingleExtends: true,
					},
				],
				'typescript/no-empty-object-type': 'error',
				'typescript/no-extra-non-null-assertion': 'error',
				'typescript/no-extraneous-class': [
					'error',
					{
						allowConstructorOnly: false,
						allowEmpty: false,
						allowStaticOnly: false,
						allowWithDecorator: true,
					},
				],
				'typescript/no-floating-promises': [
					'error',
					{
						checkThenables: true,
						ignoreVoid: true,
						ignoreIIFE: true,
					},
				],
				'typescript/no-for-in-array': 'error',
				'typescript/no-inferrable-types': 'error',
				'typescript/no-meaningless-void-operator': 'error',
				'typescript/no-misused-new': 'error',
				'typescript/no-misused-promises': [
					'error',
					{
						checksConditionals: true,
						checksVoidReturn: false,
					},
				],
				'typescript/no-namespace': 'error',
				'typescript/no-non-null-asserted-nullish-coalescing': 'error',
				'typescript/no-non-null-asserted-optional-chain': 'error',
				'typescript/no-require-imports': 'error',
				'typescript/no-this-alias': [
					'error',
					{
						allowDestructuring: true,
					},
				],
				'typescript/only-throw-error': [
					'error',
					{
						allowThrowingUnknown: true,
						allowThrowingAny: false,
					},
				],
				'typescript/no-unnecessary-boolean-literal-compare': 'error',
				'typescript/no-unnecessary-qualifier': 'error',
				'typescript/no-unnecessary-type-arguments': 'error',
				'typescript/no-unnecessary-type-assertion': 'error',
				'typescript/no-unnecessary-type-constraint': 'error',
				'typescript/no-unsafe-argument': 'error',
				'typescript/no-unsafe-assignment': 'error',
				'typescript/no-unsafe-call': 'error',
				'typescript/no-unsafe-declaration-merging': 'error',
				'typescript/no-unsafe-enum-comparison': 'error',
				'typescript/no-unsafe-function-type': 'error',
				'typescript/no-unsafe-member-access': 'error',
				'typescript/no-unsafe-return': 'error',
				'typescript/no-unsafe-type-assertion': 'error',
				'typescript/no-useless-empty-export': 'error',
				'typescript/no-useless-default-assignment': 'error',
				'typescript/no-wrapper-object-types': 'error',
				'typescript/non-nullable-type-assertion-style': 'error',
				'typescript/prefer-as-const': 'error',
				'typescript/prefer-find': 'error',
				'typescript/prefer-for-of': 'error',
				'typescript/prefer-function-type': 'error',
				'typescript/prefer-includes': 'error',
				'typescript/prefer-literal-enum-member': 'error',
				'typescript/prefer-namespace-keyword': 'error',
				'typescript/prefer-nullish-coalescing': [
					'error',
					{
						ignoreTernaryTests: false,
						ignoreConditionalTests: false,
						ignoreMixedLogicalExpressions: false,
					},
				],
				'typescript/prefer-promise-reject-errors': 'error',
				'typescript/prefer-readonly': 'error',
				'typescript/prefer-reduce-type-parameter': 'error',
				'typescript/prefer-string-starts-ends-with': 'error',
				'typescript/promise-function-async': 'error',
				'typescript/related-getter-setter-pairs': 'error',
				'typescript/restrict-plus-operands': [
					'error',
					{
						allowAny: false,
					},
				],
				'typescript/restrict-template-expressions': [
					'error',
					{
						allowNumber: true,
					},
				],
				'typescript/return-await': 'error',
				'typescript/require-array-sort-compare': [
					'error',
					{
						ignoreStringArrays: true,
					},
				],
				'typescript/strict-void-return': 'error',
				'typescript/switch-exhaustiveness-check': [
					'error',
					{
						allowDefaultCaseForExhaustiveSwitch: false,
						requireDefaultForNonUnion: true,
					},
				],
				'typescript/triple-slash-reference': [
					'error',
					{
						path: 'never',
						types: 'never',
						lib: 'never',
					},
				],
				'typescript/prefer-regexp-exec': 'error',
				'typescript/prefer-return-this-type': 'error',
				'typescript/unified-signatures': [
					'error',
					{
						ignoreDifferentlyNamedParameters: true,
					},
				],
				'typescript/use-unknown-in-catch-callback-variable': 'error',
				'capitalized-comments': 'off',
				'import/first': 'error',
				'import/no-unassigned-import': 'off',
				'import/extensions': [
					'error',
					'always',
					{
						ignorePackages: true,
					},
				],
				'import/no-absolute-path': 'error',
				'import/no-anonymous-default-export': 'off',
				'import/no-named-default': 'error',
				'import/no-webpack-loader-syntax': 'error',
				'import/no-self-import': 'error',
				'import/no-cycle': 'off',
				'import/newline-after-import': 'error',
				'import/no-amd': 'error',
				'import/no-empty-named-blocks': 'error',
				'import/no-mutable-exports': 'error',
				'promise/prefer-await-to-then': 'error',
				'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
			},
			plugins: ['import', 'promise', 'unicorn', 'typescript'],
			env: {
				es2026: true,
			},
		},
	],
};

/**
 * Disables strict type-safety rules for projects where they are too noisy.
 *
 * @type {import('oxlint').OxlintConfig}
 */
export const typescriptUnsafe = {
	overrides: [
		{
			files: [GLOBS.TS],
			rules: {
				'typescript/no-unsafe-argument': 'off',
				'typescript/no-unsafe-assignment': 'off',
				'typescript/no-unsafe-call': 'off',
				'typescript/no-unsafe-declaration-merging': 'off',
				'typescript/no-unsafe-enum-comparison': 'off',
				'typescript/no-unsafe-member-access': 'off',
				'typescript/no-unsafe-return': 'off',
				'typescript/no-unsafe-type-assertion': 'off',
			},
		},
	],
};

export default typescript;
